### ISSUE TITLE
Game crash - like MogMogCheck

### ISSUE THREAD

**Issue by Moonlight-Everlit** [Haselnussbomber/LeveHelper#11]
Log:

`2024-07-04 08:46:48.424 +02:00 [INF] [PLUGINM] Plugin was outdated, adding anyways: LeveHelper.dll
Dalamud.Plugin.Internal.Exceptions.PluginPreconditionFailedException: Unable to load LeveHelper, incompatible API level 9
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 326
   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 1667
`

**Comment by Haselnussbomber** [comment]
LeveHelper was updated, closing.
