### ISSUE TITLE
2.0.4 not showing levequests and tabs

### ISSUE THREAD

**Issue by RSPadilha** [Haselnussbomber/LeveHelper#5]
After the 2.0.4 update, the levequests are not showing no matter what and the three tabs at the top only appear when filtered by a character or phrase matching no levequest's name.
![levehelper](https://github.com/Haselnussbomber/LeveHelper/assets/15999460/697cfa68-a2ac-496e-87ad-f93dae4fafb5)

**Comment by Haselnussbomber** [comment]
Oh what!? 😳 Can you check if there are any errors in the dalamud.log (it's in %APPDATA%\XIVLauncher)?

I've released an update to fix a potential issue with loading the icons.
Other than that, I can't do much without knowing what the actual error is.

**Comment by RSPadilha** [comment]
Sorry for the delay. Dalamud.log shows:

2023-07-13 09:58:32.010 -03:00 [ERR] [LeveHelper] Unexpected exception in OnDraw
System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
   at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
   at Lumina.GameData.GetFileHash(String path)
   at Dalamud.Data.DataManager.GetFile[T](String path) in C:\goatsoft\companysecrets\dalamud\Data\DataManager.cs:line 173
   at LeveHelper.Utils.Texture.LoadTexture() in /home/runner/work/LeveHelper/LeveHelper/Utils/Texture.cs:line 90
   at LeveHelper.Utils.Texture.Draw(Nullable`1 drawSize) in /home/runner/work/LeveHelper/LeveHelper/Utils/Texture.cs:line 37
   at LeveHelper.ListTab.DrawTable() in /home/runner/work/LeveHelper/LeveHelper/Tabs/ListTab.cs:line 125
   at LeveHelper.PluginWindow.Draw() in /home/runner/work/LeveHelper/LeveHelper/PluginWindow.cs:line 122
   at Dalamud.Interface.Windowing.Window.DrawInternal(DalamudConfiguration configuration) in C:\goatsoft\companysecrets\dalamud\Interface\Windowing\Window.cs:line 317
   at Dalamud.Interface.Windowing.WindowSystem.Draw() in C:\goatsoft\companysecrets\dalamud\Interface\Windowing\WindowSystem.cs:line 152
   at LeveHelper.Plugin.OnDraw() in /home/runner/work/LeveHelper/LeveHelper/Plugin.cs:line 61

I see you update the penumbra redirect. Tested and it is working as indeed.

**Comment by Haselnussbomber** [comment]
Thank you for confirming!
I assume this solved all the problems (list and tabs)? Then we can close this issue. 🙂
